add-wg-peer: refactor and add non-interactive interface

diff --git a/add-wg-peer b/add-wg-peer
--- a/add-wg-peer
+++ b/add-wg-peer
@@ -17,20 +17,13 @@ test_input() {
 }
 
 add_peer() {
-    echo -n "Name: "
-    read name
+    local name="$1"
+    local peer="$2"
+    local allowed_ips="$3"
 
-    test_input "Name" "# " "${name}" || return 0
-
-    echo -n "PublicKey: "
-    read pubkey
-
-    test_input "PublicKey" "PublicKey = " "${pubkey}" || return 0
-
-    echo -n "AllowedIPs (including prefix length): "
-    read allowedips
-
-    test_input "AllowedIPs" "AllowedIPs = " "${allowedips}" || return 0
+    test_input "Name" "# " "${name}"
+    test_input "PublicKey" "PublicKey = " "${pubkey}"
+    test_input "AllowedIPs" "AllowedIPs = " "${allowedips}"
 
     CONFIG="[WireGuardPeer]\n"
     CONFIG+="# ${name}\n"
@@ -39,23 +32,33 @@ add_peer() {
     CONFIG+="AllowedIPs = ${allowedips}\n"
     
     echo -e "\n${CONFIG}"
-    echo -n "Add this configuration to ${NETDEV}? [Y/n] "
-    read add
 
-    if [[ -z "${add}" || "${add}" == "Y" || "${add}" == "y" ]]; then
-        echo -e "${CONFIG}" >> "${NETDEV}"
-        echo -n "OK. "
+    if [[ "${YES}" != "yes" ]]; then
+        echo -n "Add this configuration to ${NETDEV}? [Y/n] "
+        read add
+        [[ -z "${add}" || "${add}" == "y" || "${add}" == "Y" ]] || return 1
     fi
 
-    INTERFACE=$(awk '/Name = /{print $3}' ${NETDEV})
+    echo -e "${CONFIG}" >> "${NETDEV}"
 
-    echo -n "Add this configuration to running interface ${INTERFACE}? [Y/n] "
-    read add
+    # Find interface in $NETDEV
+    local interface=$(awk '/Name = /{print $3}' ${NETDEV})
 
-    if [[ -z "${add}" || "${add}" == "Y" || "${add}" == "y" ]]; then
+    # Check if interface is non-zero and actually existing
+    if [[ ${INTERFACE} && -e /sys/class/net/${INTERFACE} ]]; then
         wg set ${INTERFACE} peer ${pubkey} allowed-ips ${allowedips}
-        echo -n "OK. "
     fi
+}
+
+usage() {
+    echo "Usage: add-wg-peer [-y] [-f <file>] [<name> <public-key> <allowed-ips>]"
+    echo "    -f <file>       systemd .netdev file to edit"
+    echo "    -y              no confirmation required"
+    echo "    <name>          name of the peer - requires a valid hostname"
+    echo "    <public-key>    the PublicKey of the new peer"
+    echo "    <allowed-ips>   AllowedIPs of the new peer (allows shortcut for /32 CIDR)"
+    echo "  Without peer information, PublicKey and AllowedIPs will be queried interactively."
+    exit $1
 }
 
 if [[ $UID -ne 0 && ! $WG_TEST ]]; then
@@ -64,15 +67,71 @@ if [[ $UID -ne 0 && ! $WG_TEST ]]; then
     exit $?
 fi
 
+# use enhanced getopt
+OPTS=f:yh
+LOPTS=file:,noconfirm,help
+PARSED_OPTS=$(getopt -o $OPTS -l $LOPTS -n "$0" -- "$@")
+eval set -- "$PARSED_OPTS"
+
+# set defaults
 DEFAULT_NETDEV=${WG_TEST_FILE:-$(ls /etc/systemd/network/*.netdev | \
                                  grep -E 'wg|wireguard' | head -1)}
-NETDEV=${1:-${DEFAULT_NETDEV}}
+NETDEV=${DEFAULT_NETDEV}
+YES=n
 
-echo "Add WireGuard peer(s) to ${NETDEV##*/}"
-
-cont="y"
-while [[ "${cont}" == "y" || "${cont}" == "Y" ]]; do
-    add_peer
-    echo -n "Add another peer? [y/N] "
-    read cont
+while [[ "$1" != "--" ]]; do
+    case $1 in
+    -f|--file)
+        NETDEV="$2"
+        shift 2
+        ;;
+    -y|--noconfirm)
+        YES=yes
+        shift
+        ;;
+    -h|--help)
+        usage
+        ;;
+    *)
+        echo "Programming error" >&2
+        exit 1
+        ;;
+    esac
 done
+
+# $1 is --, $2 is name, $3 is peer, $4 is allowed-ips
+if [[ $# -gt 4 ]]; then
+    echo "Error: Too many arguments!" >&2
+    usage 1
+elif [[ $# -gt 1 && $# -lt 4 ]]; then
+    echo "Error: Too few arguments!" >&2
+    usage 1
+fi
+NAME=$2
+PEER=$3
+ALLOWED_IPS=$4
+
+if [[ -z "${PEER}" ]]; then
+    echo "Add WireGuard peer(s) to ${NETDEV}"
+
+    cont="y"
+    while [[ "${cont}" == "y" || "${cont}" == "Y" ]]; do
+        echo -n "Name: "
+        read name
+        test_input "Name" "# " "${name}" || continue
+
+        echo -n "PublicKey: "
+        read pubkey
+        test_input "PublicKey" "PublicKey = " "${pubkey}" || continue
+
+        echo -n "AllowedIPs (including prefix length): "
+        read allowedips
+        test_input "AllowedIPs" "AllowedIPs = " "${allowedips}" || continue
+
+        ! add_peer "${name}" "${pubkey}" "${allowedips}" 2>&1
+        echo -n "Add another peer? [y/N] "
+        read cont
+    done
+else
+    add_peer "${NAME}" "${PEER}" "${ALLOWED_IPS}"
+fi
