add-wg-peer: deduplicate code

diff --git a/add-wg-peer b/add-wg-peer
--- a/add-wg-peer
+++ b/add-wg-peer
@@ -4,45 +4,33 @@
 # but should be easily convertible for wg-quick
 #   created by Eicke Herbertz, 2020
 
+test_input() {
+    if [[ -z "$3" ]]; then
+        echo "$1 cannot be empty!"
+        return 1
+    fi
+
+    if grep -q "^$2$3\$" "${NETDEV}"; then
+        echo "A peer with this $1 already exists!"
+        return 1
+    fi
+}
+
 add_peer() {
     echo -n "Name: "
     read name
 
-    if [[ -z "${name}" ]]; then
-        echo "Name cannot be empty!"
-        return
-    fi
-
-    if grep -q "# ${name}" "${NETDEV}"; then
-        echo "A peer with this name already exists!"
-        return
-    fi
+    test_input "Name" "# " "${name}" || return
 
     echo -n "PublicKey: "
     read pubkey
 
-    if [[ -z "${pubkey}" ]]; then
-        echo "PublicKey cannot be empty!"
-        return
-    fi
-
-    if grep -q "${pubkey}" "${NETDEV}"; then
-        echo "A peer with this PublicKey already exists!"
-        return
-    fi
+    test_input "PublicKey" "PublicKey = " "${pubkey}" || return
 
     echo -n "AllowedIPs (including prefix length): "
     read allowedips
 
-    if [[ -z "${allowedips}" ]]; then
-        echo "AllowedIPs cannot be empty!"
-        return
-    fi
-
-    if grep -q "${allowedips}" "${NETDEV}"; then
-        echo "A peer with this AllowedIPs already exists!"
-        return
-    fi
+    test_input "AllowedIPs" "AllowedIPs = " "${allowedips}" || return
 
     CONFIG="[WireGuardPeer]\n"
     CONFIG+="# ${name}\n"
