lower-case variables

diff --git a/wg-setup-client b/wg-setup-client
--- a/wg-setup-client
+++ b/wg-setup-client
@@ -95,52 +95,52 @@ EOF
 
 command -v wg >/dev/null || error "wg not found. Please install wireguard-tools first!"
 
-OPTS=d:e:fhi:p:s
-LOPTS=descr:,endpoint:,force,help,iface:,pubkey:,server
-PARSED_OPTS=$(getopt -o $OPTS -l $LOPTS -n "$0" -- "$@")
-eval set -- "$PARSED_OPTS"
+opts=d:e:fhi:p:s
+lopts=descr:,endpoint:,force,help,iface:,pubkey:,server
+parsed_opts=$(getopt -o $opts -l $lopts -n "$0" -- "$@")
+eval set -- "$parsed_opts"
 
-WG_DESC="WireGuard VPN"
-WG_ENDPOINT=
-BACKEND=auto
-FORCE=
-WG_IFNAME=wg0
-WG_PUBLIC_KEY=
-CREATE_SERVER=
-IP_ADDRESS=
-SERVER_PORT=
+wg_description="WireGuard VPN"
+wg_endpoint=
+backend=auto
+force=
+wg_ifname=wg0
+wg_public_key=
+create_server=
+ip_address=
+server_port=
 
 while [[ "$1" != "--" ]]; do
     case $1 in
     -b|--backend)
-        BACKEND="$2"
+        backend="$2"
         shift 2
         ;;
     -d|--descr)
-        WG_DESC="$2"
+        wg_description="$2"
         shift 2
         ;;
     -e|--endpoint)
-        WG_ENDPOINT="$2"
+        wg_endpoint="$2"
         shift 2
         ;;
     -f|--force)
-        FORCE=yes
+        force=yes
         shift
         ;;
     -h|--help)
         usage
         ;;
     -i|--iface)
-        WG_IFNAME="$2"
+        wg_ifname="$2"
         shift 2
         ;;
     -p|--pubkey)
-        WG_PUBLIC_KEY="$2"
+        wg_public_key="$2"
         shift 2
         ;;
     -s|--server)
-        CREATE_SERVER=yes
+        create_server=yes
         shift
         ;;
     *)
@@ -152,11 +152,11 @@ done
 shift # away the --
 
 # All positional arguments are optional. Client setup accepts one, server setup two values.
-[[ $# -ge 1 ]] && IP_ADDRESS="$1"
-[[ $# -ge 2 ]] && SERVER_PORT="$2"
+[[ $# -ge 1 ]] && ip_address="$1"
+[[ $# -ge 2 ]] && server_port="$2"
 [[ $# -ge 3 ]] && usage 1
 # Fail when client setup is called with a second positional.
-[[ ! ${CREATE_SERVER} && -n "${SERVER_PORT}" ]] && usage 1
+[[ ! ${create_server} && -n "${server_port}" ]] && usage 1
 
 # Ensure WG_TEST is defined
 WG_TEST=${WG_TEST:-}
@@ -167,197 +167,197 @@ WG_TEST=${WG_TEST:-}
 # Now read all required parameters that weren't provided as arguments interactively
 
 # The IP address is required for both server and client
-if [[ -z "${IP_ADDRESS}" ]]; then
-    [[ ${CREATE_SERVER} ]] && \
+if [[ -z "${ip_address}" ]]; then
+    [[ ${create_server} ]] && \
         echo -n "Enter server ip address: " || \
         echo -n "Enter ip address for this client: "
-    read -r IP_ADDRESS
+    read -r ip_address
 fi
 
-[[ "${IP_ADDRESS}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]] || error "Invalid ip address"
+[[ "${ip_address}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]] || error "Invalid ip address"
 
 # Then, read the listening port for a server or a server´s public key and endpoint for a client
-if [[ ${CREATE_SERVER} ]]; then
-    if [[ -z "${SERVER_PORT}" ]]; then
+if [[ ${create_server} ]]; then
+    if [[ -z "${server_port}" ]]; then
         echo -n "Enter server listening port (empty: random port): "
-        read -r SERVER_PORT
+        read -r server_port
     fi
 
-    [[ "${SERVER_PORT}" =~ ^[0-9]{1,5}$ ]] || error "Invalid port"
+    [[ "${server_port}" =~ ^[0-9]{1,5}$ ]] || error "Invalid port"
 else
-    if [[ -z "${WG_PUBLIC_KEY}" ]]; then
+    if [[ -z "${wg_public_key}" ]]; then
         echo -n "Server PublicKey: "
-        read -r WG_PUBLIC_KEY
+        read -r wg_public_key
     fi
 
-    [[ "${WG_PUBLIC_KEY}" =~ ^[A-Za-z0-9/+]{43}=$ ]] || error "Invalid PublicKey format!"
+    [[ "${wg_public_key}" =~ ^[A-Za-z0-9/+]{43}=$ ]] || error "Invalid PublicKey format!"
 
-    if [[ -z "${WG_ENDPOINT}" ]]; then
+    if [[ -z "${wg_endpoint}" ]]; then
         echo -n "Server Endpoint: "
-        read -r WG_ENDPOINT
+        read -r wg_endpoint
     fi
 
-    [[ "${WG_ENDPOINT}" =~ ^[A-Za-z0-9.-]+:[0-9]+$ ]] || error "Invalid Endpoint (host:port)!"
+    [[ "${wg_endpoint}" =~ ^[A-Za-z0-9.-]+:[0-9]+$ ]] || error "Invalid Endpoint (host:port)!"
 fi
 
 # If subnet is provided on ip address use it
-if [[ "${IP_ADDRESS%/*}" != "${IP_ADDRESS}" ]]; then
-    IP_NETMASK="${IP_ADDRESS#*/}"
-    IP_ADDRESS="${IP_ADDRESS%/*}"
-    [[ "${IP_NETMASK}" =~ ^[0-9]{2}$ ]] || error "Invalid subnet length ${IP_NETMASK}"
+if [[ "${ip_address%/*}" != "${ip_address}" ]]; then
+    ip_netmask="${ip_address#*/}"
+    ip_address="${ip_address%/*}"
+    [[ "${ip_netmask}" =~ ^[0-9]{2}$ ]] || error "Invalid subnet length ${ip_netmask}"
 else
     echo "Warning: No subnet lenght provided, using /24!"
-    IP_NETMASK=24
+    ip_netmask=24
 fi
 
 # Calculate network from IP address and subnet length
-network_addr=$(network "${IP_ADDRESS}" "${IP_NETMASK}")
+network_addr=$(network "${ip_address}" "${ip_netmask}")
 
 # Check parsed result (TODO: write tests for the conversion and not check here)
 [[ "${network_addr}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] ||
     error "Failed to calculate network address (Result: ${network_addr})"
 
 # TODO: make this configurable
-WG_ALLOWED_IPS="${network_addr}/${IP_NETMASK}"
+wg_allowed_ips="${network_addr}/${ip_netmask}"
 
 # If backend is set to auto, check which one to use
-if [[ "$BACKEND" == "auto" ]]; then
+if [[ "$backend" == "auto" ]]; then
     if has-systemd && systemctl is-enabled systemd-networkd.service >/dev/null; then
-        BACKEND=networkd
+        backend=networkd
     else
-        BACKEND=wg-quick
+        backend=wg-quick
     fi
 fi
 
-# Setup the selected backend. The code further below will not use the $BACKEND variable directly,
+# Setup the selected backend. The code further below will not use the $backend variable directly,
 # but the WG_QUICK_CONF, WG_NETDEV and WG_NETWORK variables defined here.
 # It is possible to predefine these variables in the environment and use custom paths.
-case "$BACKEND" in
+case "$backend" in
     networkd)
         echo "Using systemd-networkd for configuration"
-        unset WG_QUICK_CONF
+        unset wg_quick_conf
 
-        WG_BASENAME=${WG_BASENAME:-90-wireguard}
-        WG_NETDEV=${WG_NETDEV:-/etc/systemd/network/${WG_BASENAME}.netdev}
-        WG_NETWORK=${WG_NETWORK:-/etc/systemd/network/${WG_BASENAME}.network}
+        wg_basename=${WG_BASENAME:-90-wireguard}
+        wg_netdev=${WG_NETDEV:-/etc/systemd/network/${wg_basename}.netdev}
+        wg_network=${WG_NETWORK:-/etc/systemd/network/${wg_basename}.network}
 
-        [[ -f "${WG_NETDEV}" && -z "${FORCE}" ]] &&
-            error "${WG_NETDEV} already exists (use -f to overwrite)!"
-        [[ -f "${WG_NETWORK}" && -z "${FORCE}" ]] &&
-            error "${WG_NETWORK} already exists (use -f to overwrite)!"
+        [[ -f "${wg_netdev}" && -z "${force}" ]] &&
+            error "${wg_netdev} already exists (use -f to overwrite)!"
+        [[ -f "${wg_network}" && -z "${force}" ]] &&
+            error "${wg_network} already exists (use -f to overwrite)!"
         ;;
     wg-quick)
         echo "Using wg-quick for configuration"
-        unset WG_NETDEV WG_NETWORK
+        unset wg_netdev wg_network
 
-        WG_QUICK_CONF=${WG_QUICK_CONF:-/etc/wireguard/${WG_IFNAME}.conf}
+        wg_quick_conf=${WG_QUICK_CONF:-/etc/wireguard/${wg_ifname}.conf}
 
-        [[ -f "${WG_QUICK_CONF}" && -z "${FORCE}" ]] &&
-            error "${WG_QUICK_CONF} already exists (use -f to overwrite)!"
+        [[ -f "${wg_quick_conf}" && -z "${force}" ]] &&
+            error "${wg_quick_conf} already exists (use -f to overwrite)!"
         ;;
     *)
-        error "Unknown backend ${BACKEND}!"
+        error "Unknown backend ${backend}!"
         ;;
 esac
 
 # The networkd configuration is split into a .network and a .netdev file, while wg-quick has only one.
-if [[ ${WG_NETWORK:-} ]]; then
-    networkd_network_header "${WG_IFNAME}" > "${WG_NETWORK}"
-    networkd_netdev_header "${WG_IFNAME}" "${WG_DESC}" > "${WG_NETDEV}"
+if [[ ${wg_network:-} ]]; then
+    networkd_network_header "${wg_ifname}" > "${wg_network}"
+    networkd_netdev_header "${wg_ifname}" "${wg_description}" > "${wg_netdev}"
 else
-    wg_quick_conf_header "${WG_IFNAME}" "${WG_DESC}" > "${WG_QUICK_CONF}"
+    wg_quick_conf_header "${wg_ifname}" "${wg_description}" > "${wg_quick_conf}"
 fi
 
 # The configuration keys and format of networkd and wg-quick are identical, only the
 # sections have different names. So we can use the same code for both.
-WG_CONF_TARGET="${WG_QUICK_CONF:-${WG_NETDEV}}"
+wg_conf_target="${wg_quick_conf:-${wg_netdev}}"
 
-# This will write an empty value if no SERVER_PORT is provided. If we bring the interface
+# This will write an empty value if no server_port is provided. If we bring the interface
 # up successfully, the actual port will be set later in the script.
-[[ ${CREATE_SERVER} ]] && echo "ListenPort = ${SERVER_PORT}" >> "${WG_CONF_TARGET}"
+[[ ${create_server} ]] && echo "ListenPort = ${server_port}" >> "${wg_conf_target}"
 
 # Generate and write the private key. We'll only keep the public key to print out at the end.
-PRIVATE_KEY="$(wg genkey)"
-PUBLIC_KEY="$(wg pubkey <<<${PRIVATE_KEY})"
-echo "PrivateKey = ${PRIVATE_KEY}" >> "${WG_CONF_TARGET}"
-unset PRIVATE_KEY
+private_key="$(wg genkey)"
+public_key="$(wg pubkey <<<${private_key})"
+echo "PrivateKey = ${private_key}" >> "${wg_conf_target}"
+unset private_key
 
 # Only the IP address goes into the network file when using systemd-networkd
-echo "Address = ${IP_ADDRESS}/${IP_NETMASK}" >> "${WG_QUICK_CONF:-${WG_NETWORK}}"
+echo "Address = ${ip_address}/${ip_netmask}" >> "${wg_quick_conf:-${wg_network}}"
 
 # Add a blank line before peer configuration
-echo >> "${WG_CONF_TARGET}"
+echo >> "${wg_conf_target}"
 
 # If configuring a client, write the server peer configuration
-[[ ! ${CREATE_SERVER} ]] && cat >> "${WG_CONF_TARGET}" <<EOF
-[${WG_NETDEV:+WireGuard}Peer]
-PublicKey = ${WG_PUBLIC_KEY}
-AllowedIPs = ${WG_ALLOWED_IPS}
-Endpoint = ${WG_ENDPOINT}
+[[ ! ${create_server} ]] && cat >> "${wg_conf_target}" <<EOF
+[${wg_netdev:+WireGuard}Peer]
+PublicKey = ${wg_public_key}
+AllowedIPs = ${wg_allowed_ips}
+Endpoint = ${wg_endpoint}
 PersistentKeepalive = 25
 
 EOF
 
 # Set permissions and ownership of the new files
-chmod 0640 "${WG_CONF_TARGET}"
-[[ -n "${WG_NETDEV:-}" && -z "${WG_TEST}" ]] && chgrp systemd-network "${WG_NETDEV}"
+chmod 0640 "${wg_conf_target}"
+[[ -n "${wg_netdev:-}" && -z "${WG_TEST}" ]] && chgrp systemd-network "${wg_netdev}"
 
 # Select which service to enable and (re)start
-if [[ -z "${WG_QUICK_CONF:-}" ]]; then
-    SERVICE="systemd-networkd.service"
+if [[ -z "${wg_quick_conf:-}" ]]; then
+    service="systemd-networkd.service"
 else
-    SERVICE="wg-quick@${WG_IFNAME}.service"
+    service="wg-quick@${wg_ifname}.service"
 fi
 
 # Enable the service if we have systemd
 if [[ ! ${WG_TEST} ]] && has-systemd; then
-    systemctl enable "${SERVICE}"
+    systemctl enable "${service}"
 fi
 
 # Check for wireguard module and try to bring up the interface
 if ! lsmod | grep ^wireguard >/dev/null && ! modprobe wireguard; then
     echo "Can't load WireGuard module! Probably the kernel got updated, please reboot!" >&2
-    if [[ ${CREATE_SERVER} && -z "${SERVER_PORT}" ]]; then
+    if [[ ${create_server} && -z "${server_port}" ]]; then
         echo "Could not start server and no port was set!" >&2
-        echo "You will have to set the ListenPort manually in ${WG_CONF_TARGET}" >&2
+        echo "You will have to set the ListenPort manually in ${wg_conf_target}" >&2
     fi
 else
     if [[ ${WG_TEST} ]]; then
-        echo "Testing: Skipping (re)starting ${SERVICE}."
+        echo "Testing: Skipping (re)starting ${service}."
     elif has-systemd && systemd-booted; then
-        echo "(Re)starting ${SERVICE}"
-        systemctl restart "${SERVICE}"
+        echo "(Re)starting ${service}"
+        systemctl restart "${service}"
     elif has-systemd; then
-        echo "systemd not booted, skipping (re)starting ${SERVICE}."
+        echo "systemd not booted, skipping (re)starting ${service}."
     else
-        echo "Installing without systemd: Running wg-quick up ${WG_IFNAME}"
-        if ! wg-quick up ${WG_IFNAME}; then
+        echo "Installing without systemd: Running wg-quick up ${wg_ifname}"
+        if ! wg-quick up ${wg_ifname}; then
             echo "Couldn't start WireGuard interface! If running in a container, probably CAP_NET_ADMIN is missing." >&2
         fi
     fi
 
     # If we are setting up a server and had no listening port provided, WireGuard will select a
     # random port which we'll extract and write it to the configuration to make it persistent.
-    if [[ ${CREATE_SERVER} && -z "${SERVER_PORT}" ]]; then
-        SERVER_PORT=$(wg show "${WG_IFNAME}" | awk '/listening port/{print $3}')
-        if [[ -z "${SERVER_PORT}" ]]; then
+    if [[ ${create_server} && -z "${server_port}" ]]; then
+        server_port=$(wg show "${wg_ifname}" | awk '/listening port/{print $3}')
+        if [[ -z "${server_port}" ]]; then
             echo "Warning: Could not determine ListenPort!" >&2
-            echo "You will have to set the ListenPort manually in ${WG_CONF_TARGET}" >&2
+            echo "You will have to set the ListenPort manually in ${wg_conf_target}" >&2
         else
-            sed -i "s/ListenPort = /ListenPort = ${SERVER_PORT}/" "${WG_CONF_TARGET}"
+            sed -i "s/ListenPort = /ListenPort = ${server_port}/" "${wg_conf_target}"
         fi
     fi
 fi
 
-if [[ ! ${CREATE_SERVER} ]]; then
+if [[ ! ${create_server} ]]; then
     echo "============================================================
 WireGuard setup successful! Server side add-peer command:
-wg-setup add-peer ${HOSTNAME} ${PUBLIC_KEY} ${IP_ADDRESS}"
+wg-setup add-peer ${HOSTNAME} ${public_key} ${ip_address}"
     exit 0
 else
     echo "============================================================
 WireGuard server setup successful!
-PublicKey: ${PUBLIC_KEY}
-ListenPort: ${SERVER_PORT}"
+PublicKey: ${public_key}
+ListenPort: ${server_port}"
     exit 0
 fi
