wg-setup: Work with wg-quick

diff --git a/wg-setup b/wg-setup
--- a/wg-setup
+++ b/wg-setup
@@ -15,7 +15,7 @@
 test_exists() {
     key="$1 = "
     [[ "$1" == "Name" ]] && key="# "
-    if grep -q "^${key}$2\$" "${NETDEV}"; then
+    if grep -q "^${key}$2\$" "${WG_NETDEV}"; then
         echo "A peer with this $1 already exists!"
         return 2
     fi
@@ -62,7 +62,7 @@ add_peer() {
     test_publickey "${peer}" 1>&2 || return $?
     test_allowedips "${allowed_ips}" 1>&2 || return $?
 
-    CONFIG="[WireGuardPeer]\n"
+    CONFIG="[${IS_NETDEV:+WireGuard}Peer]\n"
     CONFIG+="# ${name}\n"
     CONFIG+="# Added by ${SUDO_USER:-${USER}} at $(date +%F)\n"
     CONFIG+="PublicKey = ${peer}\n"
@@ -71,20 +71,16 @@ add_peer() {
     echo -e "${CONFIG}"
 
     if [[ "${YES}" != "yes" ]]; then
-        echo -n "Add this configuration to ${NETDEV}? [Y/n] "
+        echo -n "Add this configuration to ${WG_NETDEV}? [Y/n] "
         read -r add
         [[ -z "${add}" || "${add}" == "y" || "${add}" == "Y" ]] || return 1
     fi
 
-    echo -e "${CONFIG}" >> "${NETDEV}"
-
-    # Find interface in $NETDEV
-    local interface
-    interface=$(awk '/Name = /{print $3}' "${NETDEV}")
+    echo -e "${CONFIG}" >> "${WG_NETDEV}"
 
     # Check if interface is non-zero and actually existing
-    if [[ ${interface} && -e /sys/class/net/${interface} ]]; then
-        wg set "${interface}" peer "${peer}" allowed-ips "${allowed_ips}"
+    if [[ -z ${WG_TEST} && -e /sys/class/net/${WG_IFACE} ]]; then
+        wg set "${WG_IFACE}" peer "${peer}" allowed-ips "${allowed_ips}"
     fi
 }
 
@@ -95,32 +91,32 @@ remove_peer() {
     # Always print portion that is removed to stdout
     if gawk -v pk="${peer}" \
         '{ l[++n]=$0 }
-        /^\[WireGuardPeer\]$/ { if(f){ for(i=1;i<n;i++){ print l[i] } if(n>1){print ""} }
+        /^\[(WireGuard)?Peer\]$/ { if(f){ for(i=1;i<n;i++){ print l[i] } if(n>1){print ""} }
             delete l;n=1;f=0;l[n]=$0 }
         /^PublicKey/ { if($3==pk){ f=1;fs=1 } }
         /^$/ { if(f){ for(i=1;i<=n;i++){ print l[i] } } delete l;n=0;f=0 }
         END { exit !fs }' \
-        "${NETDEV}"
+        "${WG_NETDEV}"
     then
         if [[ "${YES}" != "yes" ]]; then
-            echo -n "Remove this configuration from ${NETDEV}? [y/N] "
+            echo -n "Remove this configuration from ${WG_NETDEV}? [y/N] "
             read -r del
             [[ "${del}" == "y" || "${del}" == "Y" ]] || return 1
         fi
 
-        # Remove from $NETDEV
+        # Remove from $WG_NETDEV
         gawk -i inplace -v pk="${peer}" \
             '{ l[++n]=$0 }
-            /^\[WireGuardPeer\]$/ { if(!f){ for(i=1;i<n;i++){ print l[i] } if(n>1){print ""}}
+            /^\[(WireGuard)?Peer\]$/ { if(!f){ for(i=1;i<n;i++){ print l[i] } if(n>1){print ""}}
                 delete l;n=1;f=0;l[n]=$0 }
             /^PublicKey/ { if($3==pk){ f=1;fs=1 } }
             /^$/ { if(!f){ for(i=1;i<=n;i++){ print l[i] } } delete l;n=0;f=0 }
             END { exit !fs }' \
-            "${NETDEV}"
+            "${WG_NETDEV}"
 
-        # Find interface in $NETDEV
+        # Find interface in $WG_NETDEV
         local interface
-        interface=$(awk '/Name = /{print $3}' "${NETDEV}")
+        interface=$(awk '/Name = /{print $3}' "${WG_NETDEV}")
 
         # Check if interface is non-zero and actually existing
         if [[ ${interface} && -e /sys/class/net/${interface} ]]; then
@@ -168,7 +164,7 @@ cmd_add_peer() {
     ALLOWED_IPS=$3
 
     if [[ -z "${PEER}" ]]; then
-        echo "Add WireGuard peer(s) to ${NETDEV}"
+        echo "Add WireGuard peer(s) to ${WG_NETDEV}"
 
         cont="y"
         while [[ "${cont}" == "y" || "${cont}" == "Y" ]]; do
@@ -204,7 +200,7 @@ cmd_remove_peer() {
 
     # go interactive if no peer provided
     if [[ -z "${PEER}" ]]; then
-        echo "Remove WireGuard peer(s) from ${NETDEV}"
+        echo "Remove WireGuard peer(s) from ${WG_NETDEV}"
 
         cont="y"
         while [[ "${cont}" == "y" || "${cont}" == "Y" ]]; do
@@ -227,27 +223,27 @@ cmd_list_peers() {
     FORMAT=${1:-hosts}
     case "${FORMAT}" in
     hosts)
-        awk '/^\[WireGuardPeer\]$/{getline;if($1=="#"&&$2!="Added"){name=$2}else{name="<none>"}}
+        awk '/^\[(WireGuard)?Peer\]$/{getline;if($1=="#"&&$2!="Added"){name=$2}else{name="<none>"}}
         /^AllowedIPs/{sub(/\/[0-9]+/,"",$3);printf("%-19s %s\n",$3,name)}' \
-            ${NETDEV}
+            ${WG_NETDEV}
         ;;
     added)
-        awk '/^\[WireGuardPeer\]$/{getline;if($1=="#"){
+        awk '/^\[(WireGuard)?Peer\]$/{getline;if($1=="#"){
             if($2!="Added"){name=$2;getline;if($1=="#"&&$2=="Added"){comment=$0}}
             else{name="<none>";comment=$0}}}
         /^AllowedIPs/{sub(/\/[0-9]+/,"",$3);printf("%-19s %-30s %s\n",$3,name,comment)}' \
-            ${NETDEV}
+            ${WG_NETDEV}
         ;;
     pubkeys)
-        awk '/^\[WireGuardPeer\]$/{getline;if($1=="#"&&$2!="Added"){name=$2}else{name="<none>"}}
+        awk '/^\[(WireGuard)?Peer\]$/{getline;if($1=="#"&&$2!="Added"){name=$2}else{name="<none>"}}
         /^PublicKey/{pubkey=$3}/^AllowedIPs/{sub(/\/[0-9]+/,"",$3);ip=$3}
         name&&pubkey&&ip{printf("%-19s %-30s %s\n",ip,name,pubkey);name=pubkey=ip=""}' \
-            ${NETDEV}
+            ${WG_NETDEV}
         ;;
     dns-zone)
-        awk '/^\[WireGuardPeer\]$/{getline;if($1=="#"&&$2!="Added"){name=$2}else{name="<none>"}}
+        awk '/^\[(WireGuard)?Peer\]$/{getline;if($1=="#"&&$2!="Added"){name=$2}else{name="<none>"}}
         /^AllowedIPs/{sub(/\/[0-9]+/,"",$3);printf("%-24s IN   A    %s\n",name,$3)}' \
-            ${NETDEV}
+            ${WG_NETDEV}
         ;;
     *)
         [[ "${FORMAT}" == "help" ]] || echo "Error: Unknown format ${FORMAT}!"
@@ -258,30 +254,27 @@ cmd_list_peers() {
 }
 
 # use enhanced getopt
-OPTS=f:yh
-LOPTS=file:,noconfirm,help
+OPTS=f:hi:y
+LOPTS=file:,help,iface:,noconfirm
 PARSED_OPTS=$(getopt -o $OPTS -l $LOPTS -n "$0" -- "$@")
 eval set -- "$PARSED_OPTS"
-
-# set defaults
-#shellcheck disable=SC2010
-FIRST_NETDEV=$(ls /etc/systemd/network/*.netdev | grep -E 'wg|wireguard' | head -1)
-DEFAULT_NETDEV=${WG_TEST_FILE:-${FIRST_NETDEV}}
-NETDEV=${NETDEV:-${DEFAULT_NETDEV}}
-YES=n
 
 while [[ "$1" != "--" ]]; do
     case $1 in
     -f|--file)
-        NETDEV="$2"
+        WG_NETDEV="$2"
+        shift 2
+        ;;
+    -h|--help)
+        usage
+        ;;
+    -i|--iface)
+        WG_IFACE="$2"
         shift 2
         ;;
     -y|--noconfirm)
         YES=yes
         shift
-        ;;
-    -h|--help)
-        usage
         ;;
     *)
         echo "Programming error" >&2
@@ -290,6 +283,54 @@ while [[ "$1" != "--" ]]; do
     esac
 done
 shift # away the --
+
+# With an interface, wg-setup will automatically find the target
+# configuration file and won't accept any -f argument
+if [[ -n "${WG_IFACE}" && -n "${WG_NETDEV}" ]]; then
+    echo "Error: Can't use -i and -f together!" >&2
+    exit 1
+fi
+
+# If an existing file is provided, use it and determine interface name
+if [[ -n "${WG_NETDEV}" ]]; then
+    if [[ ! -f "${WG_NETDEV}" ]]; then
+        echo "Error: ${WG_NETDEV} not found!" >&2
+        exit 1
+    fi
+    basename="${WG_NETDEV##*/}"
+    # wg-quick uses <iface>.conf as filename exclusively
+    [[ "${WG_NETDEV##*.}" == ".conf" ]] && WG_IFACE="${basename%.*}"
+    # If that didn't work, it's a .netdev file
+    [[ -z "${WG_IFACE}" ]] && WG_IFACE=$(awk '/^Name/{gsub(/Name ?= ?/,"",$0);print}')
+    # If that didn't work either, configuration is broken or we are in testing
+    if [[ -z "${WG_IFACE}" && -z "${WG_TEST}" ]]; then
+        echo "Error: Could not find interface from given configuration file!"
+        exit 1
+    fi
+    WG_IFACE=${WG_IFACE:-wg0}
+    echo "Using interface name ${WG_IFACE}"
+else
+    # No configuration file is provided, try to figure it out
+    WG_IFACE=${WG_IFACE:-wg0}
+    if [[ -z "${WG_TEST_FILE}" ]]; then
+        WG_QUICK="/etc/wireguard/${WG_IFACE}.conf"
+        WG_NETDEV=$(! grep -lR "${WG_IFACE}" /etc/systemd/network/*.netdev 2>/dev/null)
+        if [[ -f "${WG_QUICK}" && -f "${WG_NETDEV}" ]]; then
+            # Only check if systemd-networkd is enabled, as wg-quick will run without any
+            # service unit in a container
+            systemctl is-enabled systemd-networkd || WG_NETDEV="${WG_QUICK}"
+        elif [[ -f "${WG_QUICK}" ]]; then
+            WG_NETDEV="${WG_QUICK}"
+        elif [[ ! -f "${WG_NETDEV}" ]]; then
+            echo "Could not find backing config file for ${WG_IFACE}!" >&2
+            exit 1
+        fi
+    else
+        WG_NETDEV="${WG_TEST_FILE}"
+    fi
+    [[ "${WG_QUICK}" == "${WG_NETDEV}" ]] || IS_NETDEV=yes
+    #echo "Using configuration file ${WG_NETDEV}"
+fi
 
 # $1 is command
 cmd="$1"; shift || usage 1
